---
kind: auto.CI
spec:
    provider: ghaction
---
kind: common.Image
name: image-roller-derby
spec:
    extraEnvironment:
      PLATFORM: linux/amd64,linux/arm64
---
kind: common.SOPS
spec:
  enabled: true
  config: |-
    creation_rules:
      - age: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
        pgp: >-
          15D5721F5F5BAF121495363EFE042E3D4085A811,
          CC51116A94490FA6FB3C18EB2401FCAE863A06CA
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
---
kind: auto.CustomSteps
spec:
  steps:
    - name: dummy
      toplevel: true
---
kind: custom.Step
name: dummy
spec:
  makefile:
    enabled: true
    phony: true
    script:
      - |
        echo dummy
  ghaction:
    enabled: true
    jobs:
      - name: dummy
        triggerLabels:
          - integration/e2e
          - integration/dummy
      - name: dummy-a
        triggerLabels:
          - integration/e2e
          - integration/dummy-a
