secrets:
    FOO: ENC[AES256_GCM,data:pvH4,iv:PzrpYa7W0FtjUR84FVSiAHeSK9SJUhxA5p4O96C8xmo=,tag:DBQPJR9Adx5w83eG4ADtjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xrpa9ujxxcj2u2gzfrzv8mxak4rts94a6y60ypurv6rs5cpr4e4sg95f0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcDZLbjF1czJFdnU5bWha
            eVJWQ2RaVjVmZDdpblkzL2xVZWlZQzViRFZBCmVHUnJxU0VxSGNSM1JDZVJJMy9i
            RWtUTU0yMTRTTFVDcTRoanhVL2VmSDAKLS0tIDdBc3A5Sm9vSjJBWEtQN0dRMDVE
            bmVMYVlaZUJrK2hIdkpBYWxrdlVBam8KF7La5qNexfISWqZHG6aj31+YpVv4Cry8
            VWcI0prEiVvrYnHj2jEwa8yFsKcQjy2vN5oN+65/sSs8PXmzaK86ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-18T16:31:17Z"
    mac: ENC[AES256_GCM,data:MN1Lf6BYlW9vJtUow7VnmMOaqqcS1Jelu9guVg5lf+3PbCzOK1FtugqruYwLKuTy0mMmmPC2JFQLKpPRGUfUg1WI7J2jY60y5+A2hy5e3lf9wzEdR6DNepOE+O3d/cdNV/W5weer+BPhlIMDVyZI+wVDY3xiJIRCXuG88CaTPGA=,iv:3B1EKKAffz4CCqcw2Ci8LPpytGPp0XZWRke5gS9HDK8=,tag:dDkC2cqZ/NgHpkYgJXMO5g==,type:str]
    pgp:
        - created_at: "2024-04-18T16:21:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D/dYBJRlWfQISAQdANKAI34lxYW97qRyS29bP1cPv6GM0ZA4mhpk/8S+aTWsw
            gWk1I4Lxa5Z2rTpVtKkB41BomlJYKMT0I2gaJCAaOYVriUAoZOwgAt4mVoqIP+66
            0lwBaUomWbkUvmspFySkTVLOtrJJhpK+KT8t8/FcmnXUUFdoUGQ3Gz/8zsbs97Rn
            9oJ26QxiD93T7BC/SeKk9yP8fufQJejtVvdw3h6QIx7EUwR902r1or/xeYocrw==
            =Gn+6
            -----END PGP MESSAGE-----
          fp: 15D5721F5F5BAF121495363EFE042E3D4085A811
        - created_at: "2024-04-18T16:21:06Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D+EORkHurkvgSAQdAk5yw2cbBVLHzoMCuqvj5AP1XJPYCUmxezYApogsE53Iw
            J53NU1dlZtBJLSoargpSLlac0rUoNgHeUBHhPFH1vhGZSw6YEN7Bhewbdk+Rd1Xi
            0lwBiRjchK8G3Met39JCh6BH7S4Rsf/E0uqzUGTqYwDWlPxE6a13HZsJ51kfAT1Q
            uYdzG6592Y1btiIrikPGf/dT4mSkijzsFsQdvOIVLH+Lu1CaYJlpOenP6r8ypw==
            =VLLb
            -----END PGP MESSAGE-----
          fp: CC51116A94490FA6FB3C18EB2401FCAE863A06CA
    unencrypted_suffix: _unencrypted
    version: 3.8.1
