# commit to be tagged for the new release
commit = "HEAD"

project_name = "roller-derby"
github_repo = "siderolabs/roller-derby"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.0-alpha.4"
pre_release = true

# [notes]
