name: ci

on:
  push:

jobs:
  buildx:
    runs-on: self-hosted
    container:
      image: autonomy/build-container:latest
      volumes:
        - /var/ci-docker:/var/run
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0
        with:
          driver: docker-container
          endpoint: tcp://docker-amd64.ci.svc.cluster.local:2376

      - name: make base
        run: make base