"on":
  schedule:
    - cron: '*/10 * * * *'
name: download
jobs:
  default:
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          workflow: upload.yaml
          workflow_conclusion: success
          event: schedule
