"on":
  workflow_run:
    workflows:
      - upload
    types:
      - completed
name: download
jobs:
  default:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # version: 7.0.0
        with:
          name: results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display artifact content
        run: |
          ls
          cat results/run_id.txt
          echo ${{ steps.download-artifact.outputs }}
