name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on:
      - self-hosted
      - generic
    permissions:
      pull-requests: write
    # Only run for PRs, not issue comments
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: Slash Command Dispatch
      uses: peter-evans/slash-command-dispatch@v4
      with:
        token: ${{ secrets.GH_PAT }}
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        issue-type: pull-request
        commands: ok-to-test
        permission: write
