name: Ok To Test

on:
  pull_request_target:

jobs:
  ok-to-test:
    runs-on:
      - self-hosted
      - generic
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: workflow_dispatch
      with:
        workflow: ci.yaml
        ref: ${{ github.event.pull_request.head.ref }}
