concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
"on":
  schedule:
    - cron: "*/5 * * * *"
name: upload
jobs:
  default:
    runs-on:
      group: large
    steps:
      - name: create file with run id
        run: echo "run_id=${{ github.run_id }}" > run_id.txt
      - name: save artifacts
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # version: v7.0.0
        with:
          name: results
          path: |
            run_id.txt
          retention-days: "1"
